### ISSUE TITLE
1.2.0 crashes and prevents server from starting

### ISSUE THREAD

**Issue by itsdinkd** [alcatrazEscapee/cyanide#1]
pulls up a bunch of randomness in the log, preventing the server from starting. 1.1.0 works fine, 1.2.0 does not.

https://pastebin.com/CdWUPC6X

**Comment by alcatrazEscapee** [comment]
Ah, that looks like an oversight on my part.

**Comment by alcatrazEscapee** [comment]
Should be fixed as of 1.2.1, if not let me know.
