### ISSUE TITLE
Features Names aren't working. Only ??? instead of the feature

### ISSUE THREAD

**Issue by Cristelknight** [alcatrazEscapee/cyanide#10]
Cycle:
At step 9
Feature '???'
  must be before '???' (defined in '???' at index 2, 3)
  must be before '???' (defined in '???' at index 2, 3 and 2 others)

**Comment by alcatrazEscapee** [comment]
What Minecraft version?
Fabric or Forge?
Latest Log File?
What steps are you doing to get this feature cycle?
And can I have the list of mods/datapacks that you are getting a feature cycle error with?

**Comment by Cristelknight** [comment]
fabric, byg and wwoo.

**Comment by alcatrazEscapee** [comment]
Without answers to the requested questions, there's insufficient information provided to solve this issue. Nor have I been able to reproduce this locally.

**Comment by inikishev** [comment]
so its wwoo okay got it

**Comment by inikishev** [comment]
heres mine with the same error https://gist.github.com/dpe0/cc57eb5076a0587b2f250c852838b692

**Comment by inikishev** [comment]
wwoo in compatibility mode btw because it says to do that for terralith

**Comment by inikishev** [comment]
after i removed wwoo it reduced the amount of cycles but there is  still one left that says

Cycle:
At step 7
Feature '???'
  must be before '???' (defined in '???' at index 1, 2 and 3 others)
