### ISSUE TITLE
Information not being Shown Correctly

### ISSUE THREAD

**Issue by catter1** [alcatrazEscapee/cyanide#11]
TelegraphicGrunt was showing me how to use Cyanide to figure out errors when using Terralith with other mods, but the messages with the presumably important information are not being shown. I have attached an image of what is shown, the modpack used, as well as the crash log and latest.log for the user who we are trying to troubleshoot.

This is Fabric on 1.19.2.

[modpack.zip](https://github.com/alcatrazEscapee/cyanide/files/9599646/modpack.zip)
[latest.log](https://github.com/alcatrazEscapee/cyanide/files/9599610/latest.37.log)
[crash_log.txt](https://github.com/alcatrazEscapee/cyanide/files/9598389/message.11.txt)
![image](https://user-images.githubusercontent.com/63272345/191005286-aa07aeb0-bf8b-4955-83a4-a9fc557493a9.png)

Thanks!

**Comment by inikishev** [comment]
> TelegraphicGrunt was showing me how to use Cyanide to figure out errors when using Terralith with other mods, but the messages with the presumably important information are not being shown. I have attached an image of what is shown, the modpack used, as well as the crash log and latest.log for the user who we are trying to troubleshoot.
> 
> This is Fabric on 1.19.2.
> 
> [modpack.zip](https://github.com/alcatrazEscapee/cyanide/files/9599646/modpack.zip) [latest.log](https://github.com/alcatrazEscapee/cyanide/files/9599610/latest.37.log) [crash_log.txt](https://github.com/alcatrazEscapee/cyanide/files/9598389/message.11.txt) ![image](https://user-images.githubusercontent.com/63272345/191005286-aa07aeb0-bf8b-4955-83a4-a9fc557493a9.png)
> 
> Thanks!

have you fixed this? because I have the same issue
