### ISSUE TITLE
Causes crash when making new world with Incendium, on Fabric 1.19.2

### ISSUE THREAD

**Issue by TalEdd** [alcatrazEscapee/cyanide#12]
[crash-2022-09-29_23.55.43-client.txt](https://github.com/alcatrazEscapee/cyanide/files/9676314/crash-2022-09-29_23.55.43-client.txt)

Removing this mod, makes the world creation work fine.

**Comment by alcatrazEscapee** [comment]
Duplicate of #5

**Comment by TalEdd** [comment]
Noted, thank you!
