### ISSUE TITLE
Potential Incompatibility with Tectonic

### ISSUE THREAD

**Issue by border999** [alcatrazEscapee/cyanide#15]
[crash-2023-01-29_10.11.00-client.txt](https://github.com/alcatrazEscapee/cyanide/files/10530063/crash-2023-01-29_10.11.00-client.txt)

**Comment by alcatrazEscapee** [comment]
This isn't an issue with Cyanide. This is Cyanide *correctly reporting* an issue with your mods, namely, they manage to create a feature cycle. This would have crashed with or without Cyanide, all it did was identify the issue in question.


**Edit** I have now gone and reported this to the two mods that I believe to be conflicting.

**Comment by border999** [comment]
thank you
