### ISSUE TITLE
Crash on boot

### ISSUE THREAD

**Issue by t0mtee** [alcatrazEscapee/cyanide#17]
[2023-04-08-7.log](https://github.com/alcatrazEscapee/cyanide/files/11183981/2023-04-08-7.log)

**Comment by alcatrazEscapee** [comment]
You're using a mod for Minecraft 1.19.2 (cyanide-3.0.1) on Minecraft 1.19.4. Don't do that.

**Comment by t0mtee** [comment]
Ah, sorry. For some reason Prism Launcher install 3.0.1. Sorry for wasting your time
