### ISSUE TITLE
Unknown crash on 1.20.1

### ISSUE THREAD

**Issue by MelrikBirchJr** [alcatrazEscapee/cyanide#19]
Crashes when trying to create a world it was in mod list and once removed it  started to work again idk what happened but hopefully u can patch it soon

**Comment by alcatrazEscapee** [comment]
I would need to know:

- What mod version
- What loader (Forge / Fabric)
- If it crashed, provide a crash log.

To have any idea what is the issue for you.

Unfortunately I do not have psychic powers, and I cannot magically tell what is wrong with your setup. As Cyanide is meant to **improve error reporting and detection** capabilities and those capabilities don't mean squat if you just blindly ignore them.

**Comment by justastranger** [comment]
[I've replicated the crash.](https://mclo.gs/mxo5F9c)

Occurs using 4.0.0 of the mod with Quilt and its Biome API.

**Comment by alcatrazEscapee** [comment]
There is no Cyanide developed for, or tested against Quilt, at present, and you're on your own if you want to get that to work.
