### ISSUE TITLE
[1.20.1] Cyanide seems to block modded mob spawns

### ISSUE THREAD

**Issue by BugmanBugman** [alcatrazEscapee/cyanide#20]
Tested with the latest version, no modded mobs spawn. I singled it down to this mod

**Comment by SukaDaPochemuVseNikiZanyaty** [comment]
I confirm. 
Mobs from these two mods will not spawn with Cyanide:
https://github.com/AlexModGuy/AlexsMobs
https://legacy.curseforge.com/minecraft/mc-mods/exotic-birds/files

1.20.1
forge 47.1.44

**Comment by LLjo** [comment]
yep confirm here as well on 1.20.1
