### ISSUE TITLE
[1.20.1 Forge] Create's world gen features don't generate with cyanide installed.

### ISSUE THREAD

**Issue by FusionSwarly** [alcatrazEscapee/cyanide#21]
Creates custom stone world gen features don't generate in worlds when cyanide is installed.

**Comment by Mysticpasta1** [comment]
this happens in dev in my mod atlantis but for the atlantean features too

**Comment by michelsciortino** [comment]
I've found Cyanide actually breaks the registry of many mods, for example [EverlastingAbilities](https://github.com/CyclopsMC/EverlastingAbilities/issues/239)
