### ISSUE TITLE
[1.20.1 Forge] Crashes when viewing Mekanism Robit

### ISSUE THREAD

**Issue by TinyPandas** [alcatrazEscapee/cyanide#22]
https://github.com/mekanism/Mekanism/issues/7884

Cyanide causes Modded instances to crash when a "Robit" comes into view in any UI element (Creative Tab or REI/JEI Recipe View).

Was able to reproduce this consistently with just Mekanism and Cyanide installed on Forge 47.2.1 on Minecraft 1.20.1.

**Comment by Daltaxy** [comment]
+1
https://github.com/mekanism/Mekanism/issues/7894
