### ISSUE TITLE
Cyanide caused fabric server auto complete to break for OP users

### ISSUE THREAD

**Issue by purejosh** [alcatrazEscapee/cyanide#24]
Fabric server running 1.20.1, with Cyanide 4.0.0 installed. Auto complete commands no longer working for OP users. lmk if you can't recreate it.

**Comment by Tempest-5ky** [comment]
Getting the same issue with 4.1.0!

**Comment by alcatrazEscapee** [comment]
I cannot reproduce with Fabric client/server + cyanide + fabric API. Nor does cyanide make any changes to commands or command registration which makes this seem highly unlikely to be cyanide's fault.

**Comment by purejosh** [comment]
Given that I reported this a year ago, there's two reports of it on this thread, and as soon as I removed it, autocomplete worked again... Well, cyanide was involved. Was it the cause? Unsure. But it was related.
