### ISSUE TITLE
Breaking Datapack Registries

### ISSUE THREAD

**Issue by MehVahdJukaar** [alcatrazEscapee/cyanide#28]
so idk how but when this mod is on my mod own datapack registries are broken, with none of their entries registered

**Comment by alcatrazEscapee** [comment]
Is this not the same issue that was fixed by 451e7dd26a2e40d8c236874b1f670135e63ea1bf ? If not, then at the _very least_, what Minecraft version and mod loader does this occur on?

**Comment by MehVahdJukaar** [comment]
i tested yesterday on a new instance, 1.20.1. Only happens on fabric. forgot to tell
