### ISSUE TITLE
Incompatibility with Moonlight Lib

### ISSUE THREAD

**Issue by 314stacho** [alcatrazEscapee/cyanide#29]
Hello there, I started making a modpack and realized for some reason that cyanide isn´t compatible with [Moonlight Lib](https://modrinth.com/mod/moonlight)

**Comment by Cicopath** [comment]
Encountering this issue as well. Here is some relevant information:

Fabric 1.20.1-1.16.3
   API 0.92.2+1.20.1
Cyanide 4.1.0
Moonlight 2.12.17

Reason for the crash according to MoonlightLib dev:
![image](https://github.com/user-attachments/assets/aa1ad1f1-e22b-434c-9de7-7b26f1f4bfa3)

Crash log:
[crash-2024-08-28_10.59.18-server.txt](https://github.com/user-attachments/files/16786116/crash-2024-08-28_10.59.18-server.txt)

_This was not tested on a minimal instance._
