### ISSUE TITLE
Cyanide prevents server from starting

### ISSUE THREAD

**Issue by Sweetbouncedevelopment** [alcatrazEscapee/cyanide#30]
Server wont start if cyandide is in modlist.

Modloader: Forge
minecraft version: 1.20.1
Forge version: 1.20.1-47.3.0
cyanide version: cyanide-forge-1.20.1-4.1.0

latest.log :  https://gnomebot.dev/paste/231527759279685634/1269388545760428144/1269388545278214246

**Comment by James103** [comment]
Log file from the paste, as pastes on gnomebot.dev may expire after an unknown time.
[latest.log](https://github.com/user-attachments/files/16506970/latest.log)

Do you have the full mod list you're trying to start the server with?

**Comment by PikachuGabe** [comment]
I have handled someone having the issue with another mod and cyanide. It seems like something in version 4.1.0 broke com.alcatrazescapee.cyanide.codec.MixinHooks.loadAllRegistryData as that keeps causing issues with some mods or datapacks loading

**Comment by PikachuGabe** [comment]
https://github.com/alcatrazEscapee/cyanide/blob/451e7dd26a2e40d8c236874b1f670135e63ea1bf/Common/src/main/java/com/alcatrazescapee/cyanide/codec/MixinHooks.java#L83 this is the likely culprit but i am unsure of how to fix it as i cannot code java. 
Linking line 83 as that's when the failing class or mixin, as i dont know which is which, is.

**Comment by PikachuGabe** [comment]
Actually, reading the mod info, unless it starts fine with cyanide not active then cyanide shouldnt be the issue. Apparently the job of the mod is to improve error reporting.

**Comment by alcatrazEscapee** [comment]
There are datapack loading errors which cyanide has caught:

```
Errors(s) loading registry minecraft:worldgen/biome:

Not a tag id
	at: "features", step surface_structures, index 4
Not a tag id
	at: "features", step surface_structures, index 4
Not a tag id
	at: "features", step surface_structures, index 4
Not a tag id
	at: "features", step surface_structures, index 4
	at: worldgen/biome 'ad_extendra:worldgen/biome/cosmic_gaslands.json'
	at: pack 'ad_extendra-0.1.1.jar'
Not a tag id
	at: "features", step local_modifications, index 2
Not a tag id
	at: "features", step local_modifications, index 2
	at: worldgen/biome 'ad_extendra:worldgen/biome/intriguing_wastelands.json'
	at: pack 'ad_extendra-0.1.1.jar'


Errors occurred freezing registries.
These were elements that were referenced, but never defined (or their definition had an error above).

Missing references from the worldgen/biome registry: [
	'ad_extendra:cosmic_gaslands',
	'ad_extendra:intriguing_wastelands'
]
```

Note there may be cases (see #26) where cyanide is more aggressive about error reporting, but from the original report, this looks to be an error, whether caused by a mod, datapack or combination I cannot say. Without a more specific reproduction case, this does not seem like an issue with cyanide.
