### ISSUE TITLE
[1.18.2] Starting up Cyanide with the mod version of Incendium crashes my server startup

### ISSUE THREAD

**Issue by BugmanBugman** [alcatrazEscapee/cyanide#5]
https://gist.github.com/BugmanBugman/cad1f393be3de8d2a66baec6024ab291

for some reason it ONLY happens with cyanide on

**Comment by alcatrazEscapee** [comment]
So this is a bug in Incendium. It's just one that vanilla silently ignores, and Cyanide will raise issue about (Invalid optional fields). I've forwarded the issue to the dev of Incendium, they'll will likely be fixing this on their end.

In the meantime, this is just Cyanide doing what it says on the tin - catching errors.
