### ISSUE TITLE
Modrinth Support

### ISSUE THREAD

**Issue by Ecorous** [alcatrazEscapee/cyanide#8]
Post this mod on modrinth kthxbye

**Comment by alcatrazEscapee** [comment]
I have no interest or desire to do this at present.

**Comment by Ecorous** [comment]
> I have no interest or desire to do this at present.

Is there a particular reason for this, it just allows access to the mod outside of the Overwolf shithole

**Comment by alcatrazEscapee** [comment]
No, it doesn't. My mods are uploaded to the GitHub releases and allow third party downloads from CurseForge, uploading to modrinth is just a make work project which I have no interest in pursuing at present.
