### ISSUE TITLE
This is not this (maybe) mods issue, I just don't know how to contact the mod-maker or in general join a discord server about this mod

### ISSUE THREAD

**Issue by INooBTooMuch** [alcatrazEscapee/cyanide#9]
I'm using Cyanide because another mod-developer recommended it to me because I want to fix a cycle issue (I don't know what it is but the other mod-developer referred to it like this)

I'm using a datapack that shouldn't be causing any problems like this (Repurposed Structures - More Villagers Compat Datapack)
and whenever I create a world with this pack loaded it crashes. I can add the pack later on in-game and it doesn't crash but nothing gets added (not sure)

these are the logs before and after Cyanide was installed (incase there are differences otherwise ignore one) :
https://gist.github.com/INooBTooMuch/a87a9c33e027900f07c23396bfb0bf84
https://gist.github.com/INooBTooMuch/534f600f59c7903c18df2e05377740b0

I am using minecraft 1.18.2 and Cyanide 1.18.2-2.1.1

This might not be the place to post things like this but I didn't find any other way to contact the mod-developer

(Also I'm posting this not to fix the problem I have with Repurposed Structures - More Villagers Compat Datapack incase it is their fault but because I was told it should have been fixed using Cyanide, I also might not know how to use this mod so help me if possible)

**Comment by alcatrazEscapee** [comment]
Okay, so cyanide is not a error fixing mod - it's a mod to help you fix errors in your datapacks/mods. The fact that this crashes *without* cyanide, indicates you have an error (in this case, a feature cycle), and this is the problem.

Namely, this error.
```
java.lang.IllegalStateException: Feature order cycle found, involved biomes: [Reference{ResourceKey[minecraft:worldgen/biome / byg:basalt_barrera]=net.minecraft.world.level.biome.Biome@29386bb9}]
```
which cyanide shows as this error
```
Caused by: com.alcatrazescapee.cyanide.codec.FeatureCycleDetector$FeatureCycleException: A feature cycle was found.

Cycle:
At step 9
Feature '[Unknown minecraft:worldgen/placed_feature]'
  must be before '[Unknown minecraft:worldgen/placed_feature]' (defined in '[Unknown minecraft:worldgen/biome]' at index 1, 2)
```

Now, normally cyanide would be giving a better error here. Something appears to have gone wrong, and it's not (rather unfortunate). I had thought I fixed this before, but might have to look into it again if I have time and get around to it.

That aside, I believe this is actually pointing to an issue with BYG, which I've pointed out to the mod developer. This may or may not go anywhere (I could also be mistaken about that).

There's a [discord server](https://discord.gg/EWx23XqsRq) for all of my mods if you have further support questions.
